### ISSUE TITLE
create_userブランチをmainブランチに反映させたい。

### ISSUE THREAD

**Issue by sumikawa-40** [sumikawa-40/onigiri#44]
- 質問内容・実現したいこと
github pull requestsについて
create_userブランチをmainブランチに反映させたい。
- 該当ブランチ
#43 
#42 

- 現状発生している問題・質問
create_userブランチで作成したマイグレーションファイル等々がmainブランチに反映されていませんでした。
create_userブランチではマイグレーションファイルが作成されているのは確認しています。
mainブランチに反映させるため、新しくブランチを作成する方がいいのでしょうか。
同じ内容のブランチがgithub上に複数あっても問題ないのでしょうか？
また、今後の開発にあたって、同じ機能のマイグレーションファイルがブランチは違えど、同リポジトリ内にある場合は問題ないのかお聞きしたいです。

- 現状発生している問題までの経緯
create_userブランチ（以後create_userと書きます）をgithubへgit pushした後、ローカルにてgit pullをしました。
しかし、git checkout mainをした後、git pullをする所（本来mainブランチにする所）を誤って、create_userにしてしましました。
pull requestを戻して、mageを再度できるのではないかと考え、github上の pull requestのRevertボタンを押しました。
その後、再度ローカルにてgit checkout mainをした後、git pullを行いましたが、create_userで作成したマイグレーションファイルがmainブランチに反映されていませんでした。

git push〜 git pullまでの流れ

```ruby
1.git push --set-upstream origin create_user

2.github上で、pull request(UserモデルとUserテーブルを作成 #42)をmerge

3.ローカルにて、git pull（mainブランチに戻らず、create_userブランチにてgit pullをしてしまう）

4.github上で、pull request(UserモデルとUserテーブルを作成 #42)をRevert

5.ローカルにて、git checkout main

6.mainブランチにてgit pull

create_userブランチのコミットがmainブランチに反映されていない。
github上でRevertをしたため、create_userブランチはmainブランチに反映されていない？
```

現状のgitのログ

```ruby
chinatsusumikawa@MacBook-Air onigiri % git reflog
628b193 (HEAD -> create_user, origin/create_user) HEAD@{0}: checkout: moving from main to create_user
8abbe5f (origin/main, origin/HEAD, main) HEAD@{1}: checkout: moving from create_user to main
628b193 (HEAD -> create_user, origin/create_user) HEAD@{2}: checkout: moving from main to create_user
8abbe5f (origin/main, origin/HEAD, main) HEAD@{3}: pull: Fast-forward
69db72b (heroku/main) HEAD@{4}: checkout: moving from create_user to main
628b193 (HEAD -> create_user, origin/create_user) HEAD@{5}: commit: Add: TOPページのspecファイルを作成
4d0194c HEAD@{6}: commit: Add: RSpecのセットアップ
2d05f43 HEAD@{7}: commit: Fix: RSpecのセットアップのためconfig/application.rbを修正
6d72510 HEAD@{8}: commit: Add: UserモデルとUserテーブルを作成
fe6a337 HEAD@{9}: commit: Add: gem sorceryを導入
69db72b (heroku/main) HEAD@{10}: checkout: moving from main to create_user
69db72b (heroku/main) HEAD@{11}: pull: Fast-forward
721ca51 HEAD@{12}: checkout: moving from header_footer to main
6790731 (origin/header_footer, header_footer) HEAD@{13}: commit: Add: フッターの作成
2f3a182 HEAD@{14}: commit (amend): Add: ヘッダーを作成
```

- エラーから考えられる原因
github上の pull requestのRevertボタンを押したため、create_userのコミット分が取り消しされてmainブランチに反映されたと思います。
ただ、create_userに戻ると、マイグレーションファイルが作成されています。
mainブランチにマイグレーションファイルを反映させるため、再度新しいブランチでcreate_userと同じマイグレーションファイルを作成する方がいいでしょうか。
それとも、現状のcreate_userをmainブランチに再度反映させることはできるのでしょうか。

- 試したこと
git reset --hard HEAD^または、git reset --soft HEAD^をした方がいいのではと思いましたが、まだどちらもしていません。

大変お手数をおかけして申し訳ありません。ご教授をいただければと思います。

**Comment by kerochelo** [comment]
@sumikawa-40 
revertはただコミット内容を打ち消すようなコミットを上書きしただけなので、下記の記事を参考に再度進めてもらって大丈夫です。
もしくは新しくブランチを作成してそこで今回revertしてしまった内容を進めてもらっても問題ないです！
https://qiita.com/Esfahan/items/d70dabbebed851bc6978
